version: '3'

services:
  domain-db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
       - ./mysql/db-data:/var/lib/mysql
  scanner-cors:
    build:
      context: ./cors
